### ISSUE TITLE
Task-Sync 0.3.8: Can't sync tasks

### ISSUE THREAD

**Issue by Pantos** [David-Development/Task-Sync#26]
In Task-Sync 0.3.8 I always get an error while syncing:
"OK_STATEError at line 11: Cannot set timezone..."
Is it my fault or is it a bug?

**Comment by David-Development** [comment]
Thank you for the report. Should be fixed in 0.3.9. It's an issue in one of your tasks (Probably invalid structure). The sync should work anyways.
I've implemented this reporting feature because for example your login is incorrect or the server is not reachable. Since the last update you're getting a notification for such errors.
