### ISSUE TITLE
can't add account

### ISSUE THREAD

**Issue by iancustoica** [David-Development/Task-Sync#31]
Hi,

So after using the app normally I modified my server setup (added ssl). I modified the account on my phone but it throws an error "error.javax.ssl.SSLHandshakeException"

My server is baikal 0.2.6 and it is working properly with other applications (caldavzap, or on android caldav sync)

Please let me know what I should try to do.

Thank you,
Iancu

**Comment by David-Development** [comment]
Weird. Is the certificate self-signed? --> You'll have to enable the option "Allow all SSL-Certificates".
Otherwise try to remove the account. And re-add it again. (Android-->Settings-->Accounts-->TaskSync-->Delete. Android-->Settings-->Accounts-->Add-Account)

There are is a known issue when you change your ssl-certificate but as you mentioned before you were not using ssl before, right?

**Comment by iancustoica** [comment]
Hi and thank you for your reply. I had already tried what you suggested. However, after changing my certificate and fiddling with the server, I retried to connect and it worked, so in conclusion there is no problem with the app.
