### ISSUE TITLE
Sync failed

### ISSUE THREAD

**Issue by rakshazi** [David-Development/Task-Sync#33]
Hello!

Android: 4.1.2 rooted

Kernel: 3.0.8

Phone model: Fly IQ431

Firmware name: SW22 + Custom

Task-Sync: 0.4.4

OwnCloud: 7.0.3

I added new account and app tries to sync with server, but I got push message: "OwnCloud - sync failed" with description: "200 OK" O_O

How can I fix this?

Best regards, Nikita.

**Comment by David-Development** [comment]
Hello, thank you for the report. It's a strange behaviour because the "200 OK" means that the request to your server was successfull. Anyways this error occurs everytime you try to sync, right?
Please try to access the url (you've entered in the app) in your browser and try to access this site. You should be able to login and see a list with .ics files afterwards. If this is not working it might be a problem with your server.

**Comment by rakshazi** [comment]
1. Yes, it's very strange, but synchronization really fails
2. Yes, every time
3. URL valid and works good, I see *.ics list

UPD: When I try to update tasks list (swipe down), loader image shows, but nothing doing

pS: Sorry for my English, do you speak Russian?

**Comment by David-Development** [comment]
No Problem and I'm only speaking english or german. 
Weird. Is there something special in your username? Some russian characters? Probably this causes the problem. Is it possible to create a test account for me? (If yes, please send me the credentials via E-Mail to david-dev@live.de)

**Comment by rakshazi** [comment]
no, just latin letters (rakshazi), calendar name in latin too (tasks)

pS: send account credentials to your mail

**Comment by rakshazi** [comment]
Thanks! All works good!
